### ISSUE TITLE
模版内容可以修改吗？

### ISSUE THREAD

**Issue by TYUpya** [nifengxiao/MVPArmsTemplePlugin#7]
模版内容可以修改吗？目前自己使用的模板肯定是修改过一些的，所以怎样使用自己修改过的模版？

**Comment by nifengxiao** [comment]
可以修改的，具体的模板代码在src/main/kotlin/mvparms/src/app_package目录下，代码都是上传了的，修改之后直接编译生成插件即可。

**Comment by nifengxiao** [comment]
生成后的插件则在build/libs目录下

**Comment by TYUpya** [comment]
好的 知道了，谢谢！
不过个人感觉这种方式不太灵活，如果能有更便捷的方式就更棒了

**Comment by nifengxiao** [comment]
是的，哈哈，要是能做成像Live Templates那样的可视化工具一键生成对应的文件夹和文件，那就非常方便了。
